dir=/data
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=false
rpc-save-upload-metadata=true
input-file=/config/aria2.session
save-session=/config/aria2.session
save-session-interval=30
force-save=true
continue=true
auto-save-interval=30
enable-dht=true
enable-dht6=true
enable-peer-exchange=true
listen-port=6888
dht-listen-port=6888
dht-file-path=/config/dht.dat
dht-file-path6=/config/dht6.dat
max-concurrent-downloads=3
seed-time=0
file-allocation=none
disk-cache=16M
console-log-level=notice
summary-interval=0
